export const GET_RANDOM_COLOR_REQUEST = "GET_RANDOM_COLOR_REQUEST";
export const GET_RANDOM_COLOR_SUCCESS = "GET_RANDOM_COLOR_SUCCESS";
export const GET_RANDOM_COLOR_FAILURE = "GET_RANDOM_COLOR_FAILURE";